# Generated by Django 5.2.1 on 2025-06-01 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EthischeFrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage_text', models.TextField()),
                ('thema', models.CharField(max_length=200)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpielerAntwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort_text', models.TextField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EthischeDebatten.ethischefrage')),
            ],
        ),
        migrations.CreateModel(
            name='AntwortBewertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kommentar', models.TextField(blank=True)),
                ('bewertung', models.IntegerField(choices=[(1, 'Schlecht'), (2, 'Mittel'), (3, 'Gut')])),
                ('bewertender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bewertungen', to=settings.AUTH_USER_MODEL)),
                ('antwort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EthischeDebatten.spielerantwort')),
            ],
        ),
        migrations.CreateModel(
            name='TheorieText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('inhalt', models.TextField()),
                ('bezug_frage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EthischeDebatten.ethischefrage')),
            ],
        ),
    ]
