# Generated by Django 5.2.1 on 2025-06-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthischeDebatten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antwortbewertung',
            name='bewertung',
            field=models.IntegerField(choices=[(1, 'Unvertretbar'), (2, 'Okey'), (3, 'Vertretbar')]),
        ),
    ]
